# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: gpu-sharing-init-container
  labels:
    kai.scheduler/queue: default-queue
  annotations:
    gpu-fraction: "0.5"
    # Specify an init container to receive the GPU fraction allocation
    gpu-fraction-container-name: "gpu-init"
    gpu-fraction-container-type: "InitContainer"
spec:
  schedulerName: kai-scheduler
  initContainers:
    - name: gpu-init
      image: nvidia/cuda:11.0-base
      command: ["nvidia-smi"]
      args: ["-L"]
  containers:
    - name: main-app
      image: ubuntu
      args: ["sleep", "infinity"]

