{{- if .Values.postCleanup.enabled }}
# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0
apiVersion: batch/v1
kind: Job
metadata:
  name: post-delete-cleanup
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: post-delete-cleanup
    spec:
      serviceAccountName: {{ .Values.postCleanup.serviceAccountName }}
      restartPolicy: Never
      containers:
        - name: deleter
          image: "{{ .Values.global.registry }}/{{ .Values.postCleanup.image.name }}:{{ .Values.postCleanup.image.tag | default .Values.global.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.postCleanup.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              echo "Deleting deployments..."
              kubectl -n kai-scheduler delete deployment --all --ignore-not-found=true
              echo "Cleanup complete."
{{- end }}
