# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: build-pod
  labels:
    kai.scheduler/queue: default-queue
    priorityClassName: build
spec:
  schedulerName: kai-scheduler
  containers:
    - name: main
      image: ubuntu
      args: ["sleep", "infinity"]
      resources:
        limits:
          nvidia.com/gpu: "1"